# Transform for Vega-1-plus with omni drive (rotation center at robot base center)

/**:
  ros__parameters:
    map_frame: "map"
    init_frame: "lidar_init"
    init_odom_frame: "lidar_init_odom"
    vehicle_frame: "vehicle"
    laser_imu_frame: "imu_link"
    laser_frame: "lidar_3d"

    t_v_i:
      x: 0.30
      y: 0.0
      z: 0.3744

    R_v_i:
      data: [-0.766044, 0.0,  -0.642788,
             0.0, 1.0, 0.0,
             0.642788,  0.0, -0.766044]
    
    # lidar in lidar_imu frame (T_i_l, aka lidar extrinsic to lidar_imu)
    t_i_l:
      x: 0.004250
      y: 0.004180
      z: -0.004460

    R_i_l:
      data: [0.000280, -0.999993, 0.003629,
            -0.999946, -0.000242, 0.010384,
            -0.010384, -0.003632, -0.999939]